CREATE TABLE TREINAMENTO(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_FINALIZACAO DATETIME,
    TEMA VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(1000) NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
)