CREATE TABLE PRESENCA (
	DATA_MARCACAO DATETIME NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    TREINAMENTO_ID BIGINT NOT NULL,
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY(TREINAMENTO_ID) REFERENCES TREINAMENTO(ID)
)